DROP FOREIGN TABLE IF EXISTS NATION;
DROP FOREIGN TABLE IF EXISTS REGION;
DROP FOREIGN TABLE IF EXISTS PART;
DROP FOREIGN TABLE IF EXISTS SUPPLIER;
DROP FOREIGN TABLE IF EXISTS PARTSUPP;
DROP FOREIGN TABLE IF EXISTS CUSTOMER;
DROP FOREIGN TABLE IF EXISTS ORDERS;
DROP FOREIGN TABLE IF EXISTS LINEITEM;
